FROM airsharedcontainers.azurecr.io/vstsdropdownloadcore:master AS app
FROM microsoft/vsts-agent:ubuntu-16.04-docker-17.12.0-ce-standard

# Get vstsdropdownloadcore's built drop downloader application
copy --from=app /app/* /app/

RUN apt-get -qq update

# Install Python2.7 and Python2.7 dependencies
RUN apt-get -qq install -y --no-install-recommends \
                python2.7 \
                python-pip \
                python-dev

RUN wget -q https://bootstrap.pypa.io/get-pip.py
RUN python2.7 get-pip.py

RUN pip2 -q install pip==9.0.3
RUN pip2 -q install --upgrade setuptools
RUN pip2 -q install --upgrade azure azure-cli

# Install Python3 and Python 3 dependencies
RUN rm -rf ~/.cache/pip
RUN apt-get -qq install -y --no-install-recommends \
                python3 \
                python3-pip

RUN pip3 -q install --upgrade pip
RUN pip3 -q install setuptools

#task.py in aether uses appliction insights for reporting. 
RUN pip3 -q install applicationinsights==0.11.3

# Install kubctl
RUN curl -sSLO https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl

# MSFTKube
ENV MSFTKUBE_VER %%MSFTKUBE_VERSION%%

RUN rm -rf ~/.cache/pip
RUN pip3 -q install https://msftkube.blob.core.windows.net/public/msftkube-1.0.$MSFTKUBE_VER-py3-none-any.whl
