kind: Secret
apiVersion: v1
metadata:
  name: {{ template "vsts-agent.fullname" . }}
  labels:
    app: {{ template "vsts-agent.name" . }}
    chart: {{ template "vsts-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  vsts_token: {{required "VSTS Token: .Values.secrets.vstsToken required!" .Values.secrets.vstsToken | b64enc}}
